### ISSUE TITLE
Error: Invalid value for argument 2. Property 'periodInMinutes': Expected 'number' but got 'string'.

### ISSUE THREAD

**Issue by ivantsov** [ivantsov/yandex-mail-notifier#43]
https://sentry.io/alexander-nr/yandexmail-notifier/issues/291209087/

```
Error: Invalid value for argument 2. Property 'periodInMinutes': Expected 'number' but got 'string'.
  at initUnreadNotification (chrome-extension://kefdlfgiadjmihfahegpkbolhhnpkbjo/pages/background.js:1:112639)
  at Array.<anonymous> (chrome-extension://kefdlfgiadjmihfahegpkbolhhnpkbjo/pages/background.js:1:101099)
  at dispatch (chrome-extension://kefdlfgiadjmihfahegpkbolhhnpkbjo/pages/background.js:1:40847)
  at dispatch (chrome-extension://kefdlfgiadjmihfahegpkbolhhnpkbjo/pages/background.js:1:89795)
  at onNewMessage (chrome-extension://kefdlfgiadjmihfahegpkbolhhnpkbjo/pages/background.js:1:114440)
...
(3 additional frame(s) were not displayed)
```

**Comment by ivantsov** [comment]
Fixed https://github.com/ivantsov/yandex-mail-notifier/pull/46.
